;====================================================
;cBadr AI Agent
;====================================================


[from-ai-agent]
exten => s,1,NoOp(Handing call directly to AI engine)
 same => n,Set(AI_CONTEXT=demo_google_live)
 same => n,Set(AI_PROVIDER=google_live)
 same => n,Stasis(asterisk-ai-voice-agent)
 same => n,Hangup()

[from-internal-custom]
exten => 3000,1,NoOp(Intercept ext 3000 -> AI Agent)
 same => n,Goto(from-ai-agent,s,1)

;=====================================================
